14:14:00.937 INFO Test execution started: order_capturing
14:14:00.938 INFO Browser: chrome
14:14:00.938 INFO Environment: test_env
14:14:00.939 INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
14:14:04.204 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
14:14:11.439 INFO Click captureTab
14:14:15.842 INFO Waiting for 3 seconds
14:14:18.862 INFO Click startScanButton
14:14:22.483 INFO Waiting for 3 seconds
14:14:25.529 INFO Click //a[@class='startBatchScanBtn clickable']
14:14:25.595 INFO Waiting for 20 seconds
14:14:45.617 INFO Click editButton
14:14:45.748 INFO Write '4' in element //div[@class='floating-field']/input
14:14:45.837 ERROR ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=77.0.3865.120)

Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\order_capturing.py", line 23, in test
    a.send_keys(capture_tab_page.pagesInput(), a.get_element_text(capture_tab_page.imagesField))
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\actions.py", line 1621, in send_keys
    element.send_keys(text)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=77.0.3865.120)


14:14:48.370 INFO Test Result: CODE ERROR
