2019-11-15 13:31:12,339 root INFO Test execution started: captureorder_finalization
2019-11-15 13:31:12,340 root INFO Browser: chrome
2019-11-15 13:31:12,340 root INFO Environment: test_env
2019-11-15 13:31:12,341 root INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
2019-11-15 13:31:12,341 root ERROR FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexandr.may\\testdir\\projects\\some_project\\tests\\captureorder_finalization.py'
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexandr.may\\testdir\\projects\\some_project\\tests\\captureorder_finalization.py'

2019-11-15 13:31:12,343 root INFO Test Result: CODE ERROR
