13:05:14.185 INFO Test execution started: second_test
13:05:14.185 INFO Browser: chrome
13:05:14.186 INFO Environment: test_env
13:05:14.186 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
13:05:17.394 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
13:05:27.102 INFO Click addNewOrderButton
13:05:28.583 INFO Waiting for 3 seconds
13:05:31.598 INFO Click orderTypeDropdown
13:05:31.690 INFO Click //select[@id='orderTypeId']/option[text()='Plats']
13:05:33.766 INFO Click documentTypeDropdown
13:05:33.866 INFO Click //select[@id='Order_OrderItems[0]_Document_DocumentTypeId']/option[text()='CORRECTION OF PLAT (PL)']
13:05:33.941 INFO Write '1' in element numberOfPages
13:05:34.038 INFO Write '1' in element numberOfLots
13:05:34.142 INFO Click partiesTab
13:05:34.285 INFO Write 'asd' in element //input[@placeholder='First Name']
13:05:49.725 ERROR ElementNotFound: Element addToOrderButton not found using selector xpath:'//li[@id='addToOrderOuter'/input]'
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 24, in test
    a.click(new_order_page_form.addToOrderButton)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\actions.py", line 983, in click
    element = browser.get_browser().find(element)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\extended_driver.py", line 177, in find
    return common._find(self, **kwargs)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\common.py", line 122, in _find
    element_name, timeout, wait_displayed)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\common.py", line 47, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element addToOrderButton not found using selector xpath:'//li[@id='addToOrderOuter'/input]'

13:05:52.309 INFO Test Result: CODE ERROR
