2019-11-01 11:38:50,221 root INFO Test execution started: second_test
2019-11-01 11:38:50,222 root INFO Browser: chrome-remote
2019-11-01 11:38:50,222 root INFO Environment: test_env
2019-11-01 11:38:50,222 root INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
2019-11-01 11:38:50,223 root ERROR FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexandr.may\\testdir\\projects\\some_project\\tests\\second_test.py'
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexandr.may\\testdir\\projects\\some_project\\tests\\second_test.py'

2019-11-01 11:38:50,224 root INFO Test Result: CODE ERROR
